START TRANSACTION;

-- Drop fact first, then dims, then raw
DROP TABLE IF EXISTS fact_job_applications CASCADE;
DROP TABLE IF EXISTS raw_dob_job_applications CASCADE;

-- Useful for consistent date parsing
ALTER DATABASE team13_projectdb SET datestyle TO iso, ymd;

-- RAW TABLE
-- Keep raw columns as TEXT to make ingestion robust
CREATE TABLE IF NOT EXISTS raw_dob_job_applications (
    raw_id BIGSERIAL PRIMARY KEY,
    job_number TEXT,
    doc_number TEXT,
    borough TEXT CHECK (
        borough IS NULL OR TRIM(borough) IN (
            'MANHATTAN',
            'BRONX',
            'BROOKLYN',
            'QUEENS',
            'STATEN ISLAND'
        )
    ),
    house_number TEXT,
    street_name TEXT,
    block TEXT,
    lot TEXT,
    bin_number TEXT,
    job_type TEXT,
    job_status TEXT,
    job_status_descr TEXT,
    latest_action_date TEXT,
    building_type TEXT,
    community_board TEXT,
    cluster TEXT,
    landmarked TEXT,
    adult_estab TEXT,
    loft_board TEXT,
    city_owned TEXT,
    little_e TEXT,
    pc_filed TEXT,
    efiling_filed TEXT,
    plumbing TEXT,
    mechanical TEXT,
    boiler TEXT,
    fuel_burning TEXT,
    fuel_storage TEXT,
    standpipe TEXT,
    sprinkler TEXT,
    fire_alarm TEXT,
    equipment TEXT,
    fire_suppression TEXT,
    curb_cut TEXT,
    other TEXT,
    other_description TEXT,
    applicant_first_name TEXT,
    applicant_last_name TEXT,
    applicant_professional_title TEXT,
    applicant_license TEXT,
    professional_cert TEXT,
    pre_filing_date TEXT,
    paid TEXT,
    fully_paid TEXT,
    assigned TEXT,
    approved TEXT,
    fully_permitted TEXT,
    initial_cost TEXT,
    total_est_fee TEXT,
    fee_status TEXT,
    existing_zoning_sqft TEXT,
    proposed_zoning_sqft TEXT,
    horizontal_enlrgmt TEXT,
    vertical_enlrgmt TEXT,
    enlargement_sqft TEXT,
    street_frontage TEXT,
    existing_no_of_stories TEXT,
    proposed_no_of_stories TEXT,
    existing_height TEXT,
    proposed_height TEXT,
    existing_dwelling_units TEXT,
    proposed_dwelling_units TEXT,
    existing_occupancy TEXT,
    proposed_occupancy TEXT,
    site_fill TEXT,
    zoning_dist1 TEXT,
    zoning_dist2 TEXT,
    zoning_dist3 TEXT,
    special_district1 TEXT,
    special_district2 TEXT,
    owner_type TEXT,
    non_profit TEXT,
    owner_first_name TEXT,
    owner_last_name TEXT,
    owner_business_name TEXT,
    owner_house_number TEXT,
    owner_house_street_name TEXT,
    city TEXT,
    state TEXT,
    zip TEXT,
    owner_phone TEXT,
    job_description TEXT,
    dobrundate TEXT,
    job_s1_no TEXT,
    total_construction_floor_area TEXT,
    withdrawal_flag TEXT,
    signoff_date TEXT,
    special_action_status TEXT,
    special_action_date TEXT,
    building_class TEXT,
    job_no_good_count TEXT,
    gis_latitude TEXT,
    gis_longitude TEXT,
    gis_council_district TEXT,
    gis_census_tract TEXT,
    gis_nta_name TEXT,
    gis_bin TEXT,
    ingested_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- FACT TABLE
-- Typed core table for downstream use
CREATE TABLE IF NOT EXISTS fact_job_applications (
    fact_id BIGSERIAL PRIMARY KEY,
    job_number BIGINT,
    doc_number INTEGER,
    borough TEXT,
    house_number TEXT,
    street_name TEXT,
    block INTEGER,
    lot INTEGER,
    bin_number BIGINT,
    job_type TEXT,
    job_status TEXT,
    job_status_descr TEXT,
    latest_action_date TEXT,
    building_type TEXT,
    community_board VARCHAR(10),
    cluster TEXT,
    landmarked TEXT,
    adult_estab TEXT,
    loft_board TEXT,
    city_owned TEXT,
    little_e TEXT,
    pc_filed TEXT,
    efiling_filed TEXT,
    plumbing TEXT,
    mechanical TEXT,
    boiler TEXT,
    fuel_burning TEXT,
    fuel_storage TEXT,
    standpipe TEXT,
    sprinkler TEXT,
    fire_alarm TEXT,
    equipment TEXT,
    fire_suppression TEXT,
    curb_cut TEXT,
    other TEXT,
    other_description TEXT,
    applicant_first_name TEXT,
    applicant_last_name TEXT,
    applicant_professional_title TEXT,
    applicant_license TEXT,
    professional_cert TEXT,
    pre_filing_date TEXT,
    paid TEXT,
    fully_paid TEXT,
    assigned TEXT,
    approved TEXT,
    fully_permitted TEXT,
    initial_cost NUMERIC(14,2),
    total_est_fee NUMERIC(14,2),
    fee_status TEXT,
    existing_zoning_sqft NUMERIC(14,2),
    proposed_zoning_sqft NUMERIC(14,2),
    horizontal_enlrgmt TEXT,
    vertical_enlrgmt TEXT,
    enlargement_sqft NUMERIC(14,2),
    street_frontage NUMERIC(14,2),
    existing_no_of_stories NUMERIC(10,2),
    proposed_no_of_stories NUMERIC(10,2),
    existing_height NUMERIC(10,2),
    proposed_height NUMERIC(10,2),
    existing_dwelling_units INTEGER,
    proposed_dwelling_units INTEGER,
    existing_occupancy TEXT,
    proposed_occupancy TEXT,
    site_fill TEXT,
    zoning_dist1 TEXT,
    zoning_dist2 TEXT,
    zoning_dist3 TEXT,
    special_district1 TEXT,
    special_district2 TEXT,
    owner_type TEXT,
    non_profit TEXT,
    owner_first_name TEXT,
    owner_last_name TEXT,
    owner_business_name TEXT,
    owner_house_number TEXT,
    owner_house_street_name TEXT,
    city TEXT,
    state TEXT,
    zip VARCHAR(10),
    owner_phone TEXT,
    job_description TEXT,
    dobrundate TEXT,
    job_s1_no TEXT,
    total_construction_floor_area NUMERIC(14,2),
    withdrawal_flag TEXT,
    signoff_date TEXT,
    special_action_status TEXT,
    special_action_date TEXT,
    building_class TEXT,
    job_no_good_count INTEGER,
    gis_latitude DOUBLE PRECISION,
    gis_longitude DOUBLE PRECISION,
    gis_council_district TEXT,
    gis_census_tract TEXT,
    gis_nta_name TEXT,
    gis_bin TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

COMMIT;